---
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: dev
    schedule:
      interval: "daily"
    reviewers:
      - "ditkrg/devops"

  # Maintain dependencies for nuget
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: dev
    schedule:
      interval: "daily"
    reviewers:
      - "ditkrg/digital-development-net"
